import type { IconType } from "react-icons";
import {
  LuShapes,
  LuArchive,
  LuArrowRightLeft,
  LuScaling,
  LuCrop,
  LuStar,
  LuScissors,
  LuMusic,
  LuQrCode,
  LuWorkflow,
  LuVideo,
  LuClapperboard,
  LuMic,
  LuFileText,
  LuScanText,
  LuBraces,
  LuBinary,
  LuShield,
  LuEraser,
  LuKey,
  LuFingerprint,
  LuLink,
  LuCaseSensitive,
  LuCode,
  LuMessageSquare,
  LuGitCompare,
} from "react-icons/lu";

export type Tool = {
  slug: string; // route path, no leading slash
  title: string; // card title / H1 seed
  nav: string; // short nav label
  tagline: string; // card description
  icon: IconType;
};

/** Every top-level utility, used for nav, the home grid, and the sitemap. */
export const TOOLS: Tool[] = [
  {
    slug: "image-to-svg",
    title: "Image to SVG",
    nav: "Image to SVG",
    tagline: "Trace PNG, JPG & WebP into clean, scalable vector SVG.",
    icon: LuShapes,
  },
  {
    slug: "compress-image",
    title: "Compress Image",
    nav: "Compress",
    tagline: "Shrink JPG, PNG & WebP file size with a live quality preview.",
    icon: LuArchive,
  },
  {
    slug: "convert-image",
    title: "Convert Image",
    nav: "Convert",
    tagline: "Convert between PNG, JPG, WebP, AVIF, and more — output limited by input format.",
    icon: LuArrowRightLeft,
  },
  {
    slug: "resize-image",
    title: "Crop & Resize Image",
    nav: "Crop & Resize",
    tagline: "Crop to any aspect ratio and resize to exact pixels — with social presets.",
    icon: LuCrop,
  },
  {
    slug: "favicon-generator",
    title: "Favicon Generator",
    nav: "Favicon",
    tagline: "Turn any image into a multi-size favicon .ico + app icons.",
    icon: LuStar,
  },
  {
    slug: "remove-background",
    title: "Remove Background",
    nav: "Remove BG",
    tagline: "Erase a solid background to transparent in one click.",
    icon: LuScissors,
  },
  {
    slug: "batch-compress",
    title: "Batch Compress",
    nav: "Batch Compress",
    tagline: "Compress multiple images at once and download as a ZIP.",
    icon: LuArchive,
  },
  {
    slug: "batch-resize",
    title: "Batch Resize",
    nav: "Batch Resize",
    tagline: "Resize multiple images to the same dimensions in one go.",
    icon: LuScaling,
  },
  {
    slug: "convert-audio",
    title: "Audio Converter",
    nav: "Audio",
    tagline: "Convert MP3, WAV, OGG, M4A, FLAC and more — output limited by input format.",
    icon: LuMusic,
  },
  {
    slug: "upscale-image",
    title: "Upscale Image",
    nav: "Upscale",
    tagline: "Enlarge images 2×, 3×, or 4× — smooth for photos, crisp for pixel art.",
    icon: LuScaling,
  },
  {
    slug: "convert-video",
    title: "Video Converter",
    nav: "Video",
    tagline: "Convert MP4, WebM, MOV, and more — output limited by input format.",
    icon: LuVideo,
  },
  {
    slug: "video-to-gif",
    title: "Video to GIF",
    nav: "Video to GIF",
    tagline: "Convert a video clip to a smooth animated GIF with palette optimization.",
    icon: LuClapperboard,
  },
  {
    slug: "voice-recorder",
    title: "Voice Recorder",
    nav: "Record",
    tagline: "Record audio directly in your browser — no software needed.",
    icon: LuMic,
  },
  {
    slug: "qr-code-generator",
    title: "QR Code Generator",
    nav: "QR Code",
    tagline: "Generate QR codes for URLs, WiFi, vCards and more — free.",
    icon: LuQrCode,
  },
  {
    slug: "workflow",
    title: "Workflow Templates",
    nav: "Workflows",
    tagline: "Multi-step image processing: optimize, crop, resize, and convert in one click.",
    icon: LuWorkflow,
  },
  {
    slug: "merge-pdf",
    title: "Merge PDF",
    nav: "Merge PDF",
    tagline: "Combine multiple PDFs into one file — reorder pages, download instantly.",
    icon: LuFileText,
  },
  {
    slug: "split-pdf",
    title: "Split PDF",
    nav: "Split PDF",
    tagline: "Extract page ranges from a PDF without uploading to a server.",
    icon: LuFileText,
  },
  {
    slug: "pdf-to-image",
    title: "PDF to Image",
    nav: "PDF to Image",
    tagline: "Render PDF pages as PNG or JPEG images in your browser.",
    icon: LuFileText,
  },
  {
    slug: "image-to-pdf",
    title: "Image to PDF",
    nav: "Image to PDF",
    tagline: "Pack images into a single PDF with A4, Letter, or fit-to-image sizing.",
    icon: LuFileText,
  },
  {
    slug: "image-to-text",
    title: "Image to Text (OCR)",
    nav: "OCR",
    tagline: "Extract text from images and PDFs with Tesseract — 100% in your browser.",
    icon: LuScanText,
  },
  {
    slug: "json-formatter",
    title: "JSON Formatter",
    nav: "JSON",
    tagline: "Validate, pretty-print, and explore JSON with a collapsible tree view.",
    icon: LuBraces,
  },
  {
    slug: "csv-to-json",
    title: "CSV to JSON",
    nav: "CSV → JSON",
    tagline: "Convert CSV spreadsheets to JSON arrays — auto-detects delimiters.",
    icon: LuBraces,
  },
  {
    slug: "json-to-csv",
    title: "JSON to CSV",
    nav: "JSON → CSV",
    tagline: "Turn a JSON array into a downloadable CSV file.",
    icon: LuBraces,
  },
  {
    slug: "base64-encoder",
    title: "Base64 Encoder",
    nav: "Base64",
    tagline: "Encode and decode text or files to Base64 — copy or download results.",
    icon: LuBinary,
  },
  {
    slug: "remove-exif",
    title: "Remove EXIF",
    nav: "Remove EXIF",
    tagline: "View and strip GPS, camera, and other metadata before sharing photos.",
    icon: LuShield,
  },
  {
    slug: "redact-image",
    title: "Privacy Redactor",
    nav: "Redact",
    tagline: "Black out or pixelate sensitive regions on screenshots and documents.",
    icon: LuEraser,
  },
  {
    slug: "password-generator",
    title: "Password Generator",
    nav: "Password",
    tagline: "Generate secure random or memorable diceware passwords in your browser.",
    icon: LuKey,
  },
  {
    slug: "uuid-generator",
    title: "UUID Generator",
    nav: "UUID",
    tagline: "Create v4, v1, or v5 UUIDs in bulk — copy or download as text.",
    icon: LuFingerprint,
  },
  {
    slug: "url-encoder",
    title: "URL Encoder",
    nav: "URL Encode",
    tagline: "Encode or decode URL components and full URLs — instant, private.",
    icon: LuLink,
  },
  {
    slug: "url-unshortener",
    title: "URL Unshortener",
    nav: "Unshorten",
    tagline: "Preview the final destination of a short link before you click.",
    icon: LuLink,
  },
  {
    slug: "url-parser",
    title: "URL Parser",
    nav: "URL Parser",
    tagline: "Break a URL into protocol, host, path, query params, and hash.",
    icon: LuLink,
  },
  {
    slug: "text-case-converter",
    title: "Text Case Converter",
    nav: "Case Converter",
    tagline: "Convert text between camelCase, PascalCase, snake_case, kebab-case, and more.",
    icon: LuCaseSensitive,
  },
  {
    slug: "code-formatter",
    title: "Code Formatter",
    nav: "Code Formatter",
    tagline: "Format HTML, CSS, JavaScript, TypeScript, and JSON with Prettier — client-side.",
    icon: LuCode,
  },
  {
    slug: "social-media-character-counter",
    title: "Social Media Character Counter",
    nav: "Char Counter",
    tagline: "Count characters for X, LinkedIn, Instagram, and Facebook with live limit warnings.",
    icon: LuMessageSquare,
  },
  {
    slug: "diff-checker",
    title: "Diff Checker",
    nav: "Diff Checker",
    tagline: "Compare two text blocks and highlight added and removed lines side by side.",
    icon: LuGitCompare,
  },
];

/** @deprecated Image-only slugs; use CONVERSION_SLUGS from media-conversions for all media */
export { CONVERSIONS, parseConversion } from "@/lib/media-conversions";
export { CONVERSION_SLUGS } from "@/lib/media-conversions";
export type { MediaConversionInfo as ConversionInfo } from "@/lib/media-conversions";
